#!/usr/bin/env python3

import colors as c
import time
while True:
    for count in range(12):
        print(c.blue+ str(count)+ "DOG")
        time.sleep(0.37)
    for count in range(2):
        print(c.red + str(count)+ "BONE")
        time.sleep(0.55)










