#!/usr/bin/env python3

import colors as c

print(c.clear)
print('Can I guess why you are here?')

guess = input('>>> ')

if guess == 'yes':
    print('Hehe ok')

if guess == 'no':
    print('fak u')
    exit()

