#!/usr/bin/env python3

import colors as c

def live():
    print( "you may pass." )

def die():
    print( "YOU SHALL NOT PASSS")

def ask(question):
    print(question)
    answer = input('> ').strip().lower()
    return answer    


print(c.clear)

print(c.magneta+'''
Answer my questions.
''')

print(c.reset)

name = ask(c.magneta +'What is your name?')

quest = ask(c.magneta + 'what is your quest?')



if name in ['lancelot','galahad']:
    color  = ask('what is your favorite color.')
  
elif name == 'robin':
   capital = ask('What is the capital of assyria?') 
   if  capital == 'assur':
        print('You may pass.')
        live()
   else:
        die()

elif name == 'arthur':
    answer = ask('Funny or naw')
    if answer == 'funny':
        print('AWWWW YEAAAA')
    else:
        print('Sukka fool')
    
else:
    die()

