#!/usr/bin/env python3

import time
import colors as c
import sys

print(c.clear)

to = sys.argv[1] 
to = int(to)

for count in range(to + 1):
    time.sleep(1)
    print(count, c.random_color() + "seconds")  
   

