#!/usr/bin/env python3

import time

print('''You wake up on the floor in the middle of a dark three way hallway 
with a light at the end of the path way in front of you.''')

#sleep

print('A, Go forward towards the light')

print('B, Go to the left hallway')

print('C, Go to the right hallway')

main = input('> ')

if main == 'a':
  print('You exit the building then greated by a small green man in a robe')
#sleep
  print('If you want to leave then you must fetch my ingraved pendent.') 

elif main == 'b':
#sleep
    print('You reach the end of the hallway to discover a box')
#sleep
    print('A, Open the box')
    print('B, Go back')
    left = input('> ')
    
    if left == 'a':
        print('You discover a round object')
        print('You go back')
        main = input('> ')
elif main == 'c':
    print('You discover a big shadowy figure of a hulking monster staring down at you')

