#!/usr/bin/env python3

import colors as c
print(c.clear)
print(c.magneta+'Hello what is your name?')

name = input('> ').strip().lower()
if name == 'brandon jenks':
    print('longt shlong')
print(c.red+'Hello there ' +name)

if name == 'alah':
    print('BOOM')
elif name == 'brandon jenks':
    print('Hello Master')
#if name == 'brandon jenks':
#    print('Hello Master')


