#!/usr/bin/env python3

import time

print('What is your name?')
name = input('> ')

print('How old are you?')
age = input('> ')

print('lets get this straight your name is '+name+' and you are '+age+' years old?')

time.sleep(2.5)
print('Did I get this info correct? y/n')
answer = input('> ')

if answer == 'n':
    print('Ok then restart please')
    exit()
elif answer == 'y':
    print('Good, You are one step closer to getting hacked. :]')

