#!/usr/bin/env python3

import colors as c
import random
print(c.clear)

print(c.red+''' Welcome to magic eight ball!!
where all your questions will be answered correctly''')

answers = ['Yes','no','maybe']

while True:
    question = input (c.magneta+ '> ')
    answer = random.choice(answers)
    print(answer)
