#!/usr/bin/env python3

import colors as c
import random
import signal
answers = ['Yes','No','Maybe', 'Thats Silly' ]
alerts = ['Hello?? Im waiting..']
print(c.red+'''
Welcome to magic 8 ball please enter a question below
''')
def handle_alarm(sig,frame):
    alert = random.choice(alerts)
    print(c.red+alert+c.reset)
    signal.alarm(random.randrange(5,30))

signal.signal(signal.SIGALRM, handle_alarm)
while True:
    signal.alarm(10)
    question = input('> '+ c.green)
    signal.alarm(0)
    answer = random.choice(answers)
    print(c.reset, end=' ')
    print(c.red + answer +c.reset )
while True:
    question = input('> ' + c.magneta )
    answer = random.choice(answers)
    print(answer)





   
     











