#!/usr/bin/env python3
import random
import colors as c
print(c.clear)
print(c.cyan+'''Hello welcome to Brandons Magic8 Ball
Where all you questions will be answered 100% correctly''')




answers = ['Yes','No','Maybe']
while True:
  question = input(c.magneta+'> ')
  if question == ('Faggot').strip().lower():
    print('Welp your dead')
    exit()
  answers = random.choice(answers)
  print(answers)
