#!/usr/bin/env python3

import random
import colors as c
print(c.clear)
print(c.blue+''' Welcome to Magic 8 Ball!!
Please ask a question below''')


answers = ['yes','no','maybe','try again please',
'You wish','I dont think so','Eh why not',
'I rather not say','HAHAHAHAHAHAHAHHA',
'Sorry','That was kind of weird to ask',
'As far as you know','Nope','Get out',
'Dont count on it','Dont count on it',
'Better not tell you now','I dont see it','It is true',
'Get a life']


while True:
    question = input(c.red+'> ').strip().lower()
    if question == 'bye':
        print('Awe ok byeee')
        exit()

    if question in ['u suck','You Suck','You suck','you suck']:
        print(c.magneta+'ANONYMOOSE IS COMIN')
        exit()
    answer = random.choice(answers)
    print(answer)
    
        
     
