#!/usr/bin/python3
import random
import colors as c
import quiz as q
score = 0
print('Welcome to My quiz game')

questions = q.questions
while questions:
    question = random.choice(questions)
    points = question() 
    score+= points
    if points:
        questions.remove(question)


print("Congrats, score: ", score)
