#!/usr/bin/env python3

import random as r
import colors as c 

print(c.clear)

sides = [None]


sides.append('''
 ------
|      |
|  #   |
|      |
 ------
''')

sides.append('''
  ------
 |      |
 | #  # |
 |      |
  ------

''')

sides.append('''
 ------
|  #   |  
|  #   |
|  #   |
 ------

''')

sides.append('''
 ------
| #   # |
|       |
| #   # |
 ------

''')

sides.append('''
 ------
| #   # |
|   #   |
| #   # |
 ------

''')
sides.append('''
  ------
 | #  # |
 | #  # |
 | #  # |
  ------
''')

sides.append('''
 ------
|  Gaben|
|  is   |   
|  true |
|  god  |
 ------
''')

last = input

while True:
    print(c.random_color() + sides[r.randint(1,7)] + c.random_color())
    input('> ')
    print(c.clear)
    for count in range(1,6):
        print('How many sides?')
        print(input)

